### ISSUE TITLE
readEEM cannot read data file from Hitachi F7000

### ISSUE THREAD

**Issue by NganNguyenUIT** [chengvt/EEM#4]
I have a problem when using readEEM for visualizing EEM.
readEEM function cannot read the data file from Spectrophotometer Hitachi F7000 - Japanese version.
I tried to read a lot of extensions: *.csv, *.xls, *.xlsx and *.text, however, readEEM showed the error: "does not have the right format. So it will not be read.".
I used R version 3.3.1 with Mac OSX 10.11.5.
Please help me to check the issue.

Thanks in advance

**Comment by chengvt** [comment]
Could you attach a sample file for the data that you are having trouble with? I will check the format.

**Comment by NganNguyenUIT** [comment]
This is the data file with .xlsx extensions.
[DishWashing.xlsx](https://github.com/chengvt/EEM/files/352129/DishWashing.xlsx)

Please help me to check it

**Comment by chengvt** [comment]
excel file import is no longer supported from v1.1.0. I am sorry I forgot to change the description in the readme page. 

So I changed the file to csv format and was able read the file in just fine. Could it the problem be with the file/folder path specification?

**Comment by NganNguyenUIT** [comment]
I also changed the file to csv format and get the error: "'DishWashing.csv' does not have the right format. So it will not be read."
Could you please help me to check the csv file?

[DishWashing.zip](https://github.com/chengvt/EEM/files/353461/DishWashing.zip)

**Comment by chengvt** [comment]
I tried reading in the file you have attached but has no problem reading it.
If you can write the script that you have tried, I will see if there is any problem with file path.

**Comment by NganNguyenUIT** [comment]
I think the problem is the .csv file that I generated is not encoded UTF-8.
I tried to change the xlsx file to csv file with encoding UTF-8 and the readEEM function works normally.
Thank you so much for your support!

**Comment by chengvt** [comment]
No problem. Glad it works!
