### ISSUE TITLE
readEEM can not read the raw eem .txt data file 

### ISSUE THREAD

**Issue by songua** [chengvt/EEM#6]
[FL DI.txt](https://github.com/chengvt/EEM/files/3242107/FL.DI.txt)
Hi, attached is my eem data file, I got the warning message when I tried to visualize the data using the command "data <-readEEM("C:\\data")".
Warning message:
In readSingleEEM(file) :
  'FL DI 1.txt' does not have the right format. So it will not be read.
the R version is 3.4.4 and I use windows 10.
Please help me check the issue.
Thank you.

**Comment by chengvt** [comment]
Hi Songua,

I looked at the file format and it looks similar to [Horiba Aqualog file](https://github.com/chengvt/EEM/blob/master/inst/tests/data_format/horiba_aqualog.dat) except that the extension is different. If you change the extension from *.txt to *.dat, `readEEM` should be able to read the file. I'm sorry I could only suggest a hack-like solution at the moment.

Regards

**Comment by songua** [comment]
Hi chengvt,
Thank you for your rapid reply.
I changed the extension to *dat, and readEEM works this time, but when I use the class() function to check the data type, the result is "character", then drawEEM does not work since it is an object of class "character".  Do you know how do I fix this?
Best,

**Comment by chengvt** [comment]
Could you show the scripts you have tried? I tried the following and was able to make a plot.

```
## import file
dat <- readEEM("file.dat")

## test the import by plotting
drawEEM(dat, 1)
```

**Comment by songua** [comment]
It works now.  Thank you so much. So my scripts is:
readEEM("file.dat")
drawEEM("file.dat", 1)
Do you mind explain why it does not work in this way？

**Comment by chengvt** [comment]
Glad it works!

> Do you mind explain why it does not work in this way？
It's because the first argument of `drawEEM` only accepts an object of `EEM` class which "file.dat", a character class object, is not. The object of EEM class can be created via `readEEM` function. Please refer to the function's help page for more details.

**Comment by songua** [comment]
Ok, thank you
